const constants = {
    ADD_POST : 'ADD-POST',
    UPDATE_NEW_POST_TEXT : 'UPDATE-NEW-POST-TEXT',
    UPDATE_NEW_MESSAGE_BODY : 'UPDATE-NEW-MESSAGE-BODY',
    SEND_MESSAGE : 'SEND-MESSAGE',
    FOLLOW : 'FOLLOW',
    UNFOLLOW : 'UNFOLLOW',
    SET_USERS : 'SET_USERS',
    SET_CURRENT_PAGE : 'SET_CURRENT_PAGE',
    SET_USERS_COUNT : 'SET_USERS_COUNT',
    TOGGLE_IS_FETCHING : 'TOGGLE_IS_FETCHING',

    SET_USER_PROFILE : 'SET_USER_PROFILE',

    SET_USER_DATA : 'SET_USER_DATA'
}

export default constants;
