const constants = {
    ADD_POST : 'ADD-POST',
    UPDATE_NEW_POST_TEXT : 'UPDATE-NEW-POST-TEXT',
    UPDATE_NEW_MESSAGE_BODY : 'UPDATE-NEW-MESSAGE-BODY',
    SEND_MESSAGE : 'SEND-MESSAGE',
    FOLLOW : 'FOLLOW',
    UNFOLLOW : 'UNFOLLOW',
    SET_USERS : 'SET_USERS'
}

export default constants;
